project:
  type: website

website:
  title: "ML-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ML_notebook.qmd
        text: Notes
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



